name: Java CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mvn -v
      - run: mvn --batch-mode --no-transfer-progress verify
      - run: java -cp target/my-app-1.0-SNAPSHOT.jar com.github.fwilhe.Dummy
      - run: mvn --batch-mode --no-transfer-progress exec:java -Dexec.mainClass="com.github.fwilhe.Dummy"
